esphome:
  name: laundry-bridge

esp8266:
  board: d1_mini

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
#  encryption:
#    key: "TZn0rOGyjjt+QJRU1IeoWENkdcUkkwl3CdqLAgds9KE="

ota:
  password: !secret esp_home_ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

remote_receiver:
  pin:
    number: D6
    inverted: true
    mode:
      input: true
      pullup: true
  dump:
    - lg:
    - samsung:
#    - nec  
remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

mqtt:
  broker: 192.168.2.250
  on_message:
    topic: lounge-receiver/ir/receive
    then:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: !lambda |-
          std::string str = x;
          std::vector<int> v;
          char * token;
          char seps[] = ",";
          token = strtok (&str[0],seps);
          while (token != NULL)
          {
            v.push_back( atoi(token) );
            token = strtok (NULL, seps);
          }
          return v;

switch:
  - platform: template
    name: "Samsung TV Power ON"
    turn_on_action:
      remote_transmitter.transmit_samsung:
        data: 0xE0E09966
  - platform: template
    name: "Samsung TV Power OFF"
    turn_on_action:
      remote_transmitter.transmit_samsung:
        data: 0xE0E019E6
