esphome:
  name: lounge-receiver

esp8266:
  board: d1_mini

# Enable logging
logger:

web_server:
  port: 80

api:

ota:
  password: !secret esp_home_ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

remote_receiver:
  pin:
    number: D4
    inverted: true
    mode:
      input: true
      pullup: true
  
  dump: nec

  on_raw:
    then:
    - mqtt.publish:
        topic: lounge-receiver/ir/receive
        payload: !lambda |-
          std::vector<int> rxv = x;
          std::string rxstr;
          for (size_t i = 0; i < rxv.size(); i++) {
            rxstr.append(to_string(rxv[i]));
            if (i < (rxv.size()-1)) {
              rxstr.append(",");
            }
          }
          return rxstr;

mqtt:
  broker: 192.168.2.250


